---
name: 'Docker-build-release'
description: 'Build Docker image and push to repository'
inputs:
  registry:
    description: 'Registry to which image will be pushed'
    default: ghcr.io/uclahs-cds
  metadata-file:
    description: 'Metadata YAML file containing information'
    default: metadata.yaml
  image-name-key-path:
    description: 'YAML path to key for image name'
    default: '.image_name'
  github-token:
    description: 'GITHUB_TOKEN for access'
    default: ${{ github.token }}
  custom-tags:
    description: 'Custom tags'
    default: ''
  context:
    description: 'Docker build context'
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Read YAML
      id: yaml-data
      uses: mikefarah/yq@v4
      with:
        cmd: yq '${{ inputs.image-name-key-path }}' '${{ inputs.metadata-file }}'

    # Take this path if the event is a deletion
    - if: github.event_name == 'delete'
      name: Delete matching docker tags
      uses: actions/github-script@v7
      with:
        script: |
          const script = require("${GITHUB_ACTION_PATH}/delete-tags.js')
          console.log(script({github, context}))

    # Take this path if the event is a push
    - name: Create tags
      if: github.event_name != 'delete'
      id: meta
      uses: docker/metadata-action@v5
      with:
        flavor: |
          latest=false
        images: ${{ inputs.registry }}/${{ steps.yaml-data.outputs.result }}
        tags: |
          type=raw,enable=${{github.event_name == 'push'}},value=dev,event=branch
          type=match,pattern=v(.*),group=1
          ${{ inputs.custom-tags }}

    - name: Log in to the Container registry
      if: github.event_name != 'delete'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build and push Docker image
      if: github.event_name != 'delete'
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
