---
name: 'Docker-build-release'
description: 'Build Docker image and push to repository'
inputs:
  registry:
    description: 'Registry to which image will be pushed'
    default: ghcr.io/uclahs-cds
  metadata-file:
    description: 'Metadata YAML file containing information'
    default: metadata.yaml
  image-name-key-path:
    description: 'YAML path to key for image name'
    deafult: "["image_name"]"
  github-token:
    description: 'GITHUB_TOKEN for access'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read YAML
      id: yaml-data
      uses: jbutcher5/read-yaml@1.6
      with:
        file: ${{ inputs.metadata-file }}
        key-path: ${{ inputs.image-name-key-path }}

    - name: Create tags
      id: meta
      uses: docker/metadata-action@v3
      with:
        flavor: |
          latest=false
        images: ${{ inputs.registry }}/${{ steps.yaml-data.outputs.data }}
        tags: |
          type=raw,enable=${{github.event_name == 'push'}},value=dev,event=branch
          type=match,pattern=v(.*),group=1
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
