---
name: CI

on:
  push:
    branches:
      - main
      - refactor-base
  pull_request:
    branches:
      - main
      - refactor-base

jobs:
  CICD-base:
    runs-on: ubuntu-latest

    steps:
      - uses: uclahs-cds/tool-static-analysis@v1
